services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    env_file:
      - .env

    ports:
      - 3000:3000